services:
  elk-data3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elk-data3
    volumes:
      - type: bind
        source: ./elasticsearch-data3.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: data3
        target: /usr/share/elasticsearch/data
      - type: volume
        source: certs
        target: /usr/share/elasticsearch/config/certificates
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      ELASTIC_PASSWORD: ${password_elasticsearch}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"
    ports:
      - "9200:9200"
      - "9300:9300"
volumes:
  data3:
    driver: local
  certs:
    driver: local