version: '3.3'
services:
  elk-data03:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elk-data03
    volumes:
      - ./elasticsearch-elk-data02.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ${ES_DATA}:/usr/share/elasticsearch/data:rw
      - ${ES_LOGS}:/usr/share/elasticsearch/log:rw
      - ${PATH_REPO}:/usr/share/elasticsearch/snapshots:rw
      - ${CERTS_DIR}:/usr/share/elasticsearch/config/certs:ro
    environment:
      cluster.name: ${CLUSTER_NAME}
      ELASTIC_PASSWORD: ${PASS_ELASTIC}
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      xpack.license.self_generated.type: ${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"
    ports:
      - "${ES_PORT}:${ES_PORT}"
      - "${ES_TRANSPORT_PORT}:${ES_TRANSPORT_PORT}"