version: '2.2'

services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    command: >
      bash -c '
        if [[ ! -f config/certs/ca.zip ]]; then
          bin/elasticsearch-certutil ca  --silent --pem --in config/certificates/instances.yml -out /certs/ca.zip;
          unzip /certs/ca.zip -d /certs;
        fi;
        chown -R 1000:0 /certs
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/certs', '.:/usr/share/elasticsearch/config/certs']

volumes: {"certs"}