version: '3.3'
services:
  elk-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elk-master
    volumes:
      - ./elasticsearch-elk-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /elk-masterdb/data/:/usr/share/elasticsearch/data:rw
      - /elk-masterdb/logs/:/usr/share/elasticsearch/logs:rw
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"
    ports:
      - "9200:9200"
      - "9300:9300"