version: '2.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
      - ${ES_DATA}:/usr/share/elasticsearch/data:rw
      - ${ES_LOGS}:/usr/share/elasticsearch/logs:rw
      - ${PATH_REPO}:/usr/share/elasticsearch/snapshots:rw
      - ${CERTS_DIR}:/usr/share/elasticsearch/config/certs:ro
    ports:
      - ${ES_PORT}:${ES_PORT}
      - ${ES_TRANSPORT_PORT}:${ES_TRANSPORT_PORT}
    environment:
      - cluster.name=${CLUSTER_NAME}
      - ELASTIC_PASSWORD=${PASS_ELASTIC}
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:rw
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ${CERTS_DIR}:/usr/share/logstash/certs:ro
    ports:
      - "${LOGSTASH_PORT}:${LOGSTASH_PORT}/tcp"
      - "${LOGSTASH_PORT}:${LOGSTASH_PORT}/udp"
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    network_mode: "host"

    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ${KIBANA_DIR}:/usr/share/kibana/data:rw
      - ${CERTS_DIR}:/usr/share/kibana/config/certs:ro
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${PASS_KIBANA}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    network_mode: "host"
    depends_on:
      - elasticsearch