---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#
server.name: elk-logstash01
http.host: "10.10.10.13"
path.config: /usr/share/logstash/pipeline